[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(message)s"

log_file = "pytest.log"
log_file_level = "DEBUG"
# https://docs.python.org/3/library/logging.html#logrecord-attributes
log_file_format = "%(asctime)s %(relativeCreated)d [%(levelname)8s] (%(filename)s:%(lineno)s::%(funcName)s) %(message)s"
log_file_date_format = "%Y-%m-%d %H:%M:%S"
